---
- name: Ensure chocolatey is installed
  win_chocolatey:
    name:
    - chocolatey
    - chocolatey-core.extension
    state: present

#- name: Ensure user bob is present
#  win_user:
#    name: bob
#    password: StrongPass123!
#    password_never_expires: yes
#    state: present
#    groups:
#      - Administrators
#  ignore_errors: yes

#- name: Ensure user alice is present
#  win_user:
#    name: alice
#    password: StrongPass123!
#    password_never_expires: yes
#    state: present
#    groups:
#      - Administrators
#  ignore_errors: yes

#- name: Ensure user Administrator is present with a valid password
#  win_user:
#    name: Administrator
#    password: StrongPass123!
#    password_never_expires: yes
#    state: present
#    groups:
#      - Administrators
#  ignore_errors: yes

- name: disable enhanced exit codes
  win_chocolatey_feature:
    name: useEnhancedExitCodes
    state: disabled

- name: Install multiple packages sequentially
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
  - notepadplusplus
  - putty
  - python
  - git
  - 7zip
  - sysinternals
  - wget
  - pstools

- name: Check if mimikatz exists
  win_stat:
    path: C:\mimikatz.zip
  register: mimikatz

- name: Download mimikatz if it does not exists
  win_shell: Invoke-WebRequest -Uri https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20200918-fix/mimikatz_trunk.zip -OutFile C:\mimikatz.zip
  when: not mimikatz.stat.exists

- name: Change the hostname to dc01
  win_hostname:
    name: dc01
  register: win_hostname

- name: Reboot
  win_reboot:
  when: win_hostname.reboot_required
