---
- name: cyberloop.local Domain Controller configuration
  hosts: domain_controller
  serial: 1
  roles:
  - common
  - domain_controller

  tasks:
  - name: Check for xDnsServer Powershell module
    win_psmodule:
      name: xDnsServer
      repository: PSGallery
      state: present

  - name: Configure DNS Forwarders
    win_dsc:
      resource_name: xDnsServerForwarder
      IsSingleInstance: "yes"
      UseRootHint: false
      IPAddresses:
        - "1.1.1.1"
        - "8.8.8.8"

  - name: Ensure that admin@cyberloop.local is present as Domain Admin
    win_domain_user:
      name: admin
      password: StrongPass123!
      password_never_expires: yes
      state: present
      path: cn=Users,dc=CYBERLOOP,dc=local
      groups:
        - Domain Admins

  - name: Ensure that bob@cyberloop.local is present in OU cn=Users,dc=CYBERLOOP,dc=local
    win_domain_user:
      name: bob
      password: StrongPass123!
      password_never_expires: yes
      state: present
      path: cn=Users,dc=CYBERLOOP,dc=local
      groups:
        - Users

  - name: Ensure that alice@cyberloop.local is present in OU cn=Users,dc=CYBERLOOP,dc=local
    win_domain_user:
      name: alice
      password: StrongPass123!
      password_never_expires: yes
      state: present
      path: cn=Users,dc=CYBERLOOP,dc=local
      groups:
        - Users

  - name: Create AllTeams group
    win_domain_group:
      name: allTeams
      scope: global
      path: DC=cyberloop,DC=local
      state: present

  - name: Create DBAOracle
    win_domain_group:
      name: DBAOracle
      scope: global
      path: DC=cyberloop,DC=local
      state: present

  - name: Create DBASQLServer
    win_domain_group:
      name: DBASQLServer
      scope: global
      path: DC=cyberloop,DC=local
      state: present

  - name: Create DBAMongo group
    win_domain_group:
      name: DBAMongo
      scope: global
      path: DC=cyberloop,DC=local
      state: present

  - name: Create DBARedis group
    win_domain_group:
      name: DBARedis
      scope: global
      path: DC=cyberloop,DC=local
      state: present

  - name: Create DBAEnterprise Group ...
    win_domain_group:
      name: DBAEnterprise
      scope: global
      path: DC=cyberloop,DC=local
      state: present

  - name: Create a Test Group ...
    win_domain_group:
      name: HoneypotGroup
      scope: global
      path: DC=cyberloop,DC=local
      state: present
