---

- name: alebov.local workstation configuration
  hosts: workstation

  roles:
    - commonwkstn

  tasks:

  - name: Set configure dns
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses:
      - 192.168.56.10
      log_path: C:\dns_log.txt

  - name: Ensure directory structure for public share exists
    win_file:
      path: C:\shares\public
      state: directory

  - name: Ensure public share exists
    win_share:
      name: public
      description: Basic RW share for all domain users
      path: C:\shares\public
      list: yes
      full: Administrators
      change: Users

  - name: add windows 10 workstation to alebov.local
    win_domain_membership:
      dns_domain_name: alebov.local
      domain_admin_user: admin@alebov.local
      domain_admin_password: StrongPass123!
      state: domain
    register: domain_state

  - name: reboot workstation if needed
    win_reboot:
    when: domain_state.reboot_required
