- name: Change the hostname to domain-controller
  win_hostname:
    name: domain-controller
  register: win_hostname

- name: Reboot
  win_reboot:
  when: win_hostname.reboot_required
  
- name: Ensure that Administrator is present with a valid password
  win_user:
    name: Administrator
    password: StrongPass123!
    password_never_expires: yes
    state: present
  ignore_errors: yes

- name: Ensure that cyberloop.local domain exixts
  microsoft.ad.domain:
    dns_domain_name: cyberloop.local
    safe_mode_password: StrongPass123!
  register: check_domain

- name: Reboot machine
  win_reboot:
  when: check_domain.changed

# Param 'log_path' is deprecated. See the module docs for more information. This feature will be removed from ansible.windows in a release after 2022-07-01. Deprecation warnings can be disabled by  setting deprecation_warnings=False in ansible.cfg.
- name: Ensure the server is a domain controller
  microsoft.ad.domain_controller:
    dns_domain_name: cyberloop.local
    domain_admin_user: Administrator@cyberloop.local
    domain_admin_password: StrongPass123!
    safe_mode_password: StrongPass123!
    state: domain_controller
  register: check_domain_controller

- name: Reboot machine
  win_reboot:
  when: check_domain_controller.changed

