# Adjust your timezone
- name: Set timezone to Europe/Rome
  timezone:
    name: Europe/Rome
  become: yes

#- name: Add multiverse repository
#  shell: apt-add-repository multiverse -y
#  args:
#    executable: /bin/bash
#  become: yes

- name: Update and upgrade apt packages
  apt:
    upgrade: "yes"
    update_cache: yes
  become: yes

- name: Install important tools
  apt:
    name: ["python3", "python3-pip", "jq", "git", "curl"]
    state: present
  become: yes
