- name: Install NuGet if necessary
  ansible.windows.win_shell: |
    $providers = (Get-PackageProvider | Where-Object -Property Name -Match nuget)
    if ($providers -eq $null) {
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -Scope AllUsers
    }
  changed_when: False

# See https://github.com/ansible-collections/community.windows/issues/340
- name: Install upgraded PowershellGet if necessary
  ansible.windows.win_shell: |
    $module = Get-Module -ListAvailable -Name 'PowerShellGet' | Sort-Object -Property Version -Descending | Select-Object -First 1
    if ($module -eq $null -or $module.Version -le [Version]'1.0.0.1') {
        Install-Module -Name 'PowerShellGet' -Repository 'PSGallery' -Scope 'AllUsers' -AllowClobber -Force -Confirm:$false
    }
  changed_when: False

  ## EXAMPLE
  #- name: Install or update an existing PSWindowsUpdate module to the newest version
  #  community.windows.win_psmodule:
  #    name: PSWindowsUpdate
  #    state: latest
  #    accept_license: True


- name: Windows | Check for xRemoteDesktopAdmin Powershell module
  win_psmodule:
    name: xRemoteDesktopAdmin
    state: present

- name: Windows | Enable Remote Desktop
  win_dsc:
    resource_name: xRemoteDesktopAdmin
    Ensure: present
    UserAuthentication: Secure

- name: Windows | Check for xNetworking Powershell module
  win_psmodule:
    name: xNetworking
    state: present

- name: Firewall | Allow RDP through Firewall
  win_dsc:
    resource_name: xFirewall
    Name: "Administrator access for RDP (TCP-In)"
    Ensure: present
    Enabled: True
    Profile: "Domain"
    Direction: "Inbound"
    Localport: "3389"
    Protocol: "TCP"
    Description: "Opens the listener port for RDP"

- name: Change the hostname to win-workstation-1
  win_hostname:
    name: win-workstation-1
  register: res

- name: Reboot
  # In case it stucks here saying "A system shutdown was in progress", reboot manually the vm and launch the playbook again
  win_reboot:
    reboot_timeout: 2000
  when: res.reboot_required

- name: Ensure chocolatey is installed
  win_chocolatey:
    name:
    - chocolatey
    - chocolatey-core.extension
    state: present

- name: Install multiple packages sequentially
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
  - notepadplusplus
  - git
  - pstools

